name: DB Seed

on:
  push:
    branches:
      - main

jobs:
  seed:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[db-seed]')
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prisma generate

      - run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - run: pnpm prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ROOT_USER_EMAIL: ${{ secrets.ROOT_USER_EMAIL }}
          ROOT_USER_PASSWORD: ${{ secrets.ROOT_USER_PASSWORD }}
          ROOT_USER_NAME: ${{ secrets.ROOT_USER_NAME }}
